source.. = src/
bin.includes = META-INF/,\
               .,\
               WebContent/,\
               src/,\
               build/,\
               build.properties,\
               .svn/,\
               .settings/,\
               .project,\
               .classpath
src.includes = WebContent/,\
               src/,\
               build/,\
               .project,\
               .classpath,\
               .settings/,\
               .svn/,\
               META-INF/,\
               build.properties
